### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#10]
Hello,

Can you please let me know how to run this app. I could not see an entry in package.json or Makefile. I tried `npm server`, and it seems started, but go this error in terminal. 

```
development.js:19react-transform-webpack-hmr has been renamed to react-transform-hmr. Please change the dependency name in package.json and your Babel configuration.(anonymous function) @ development.js:19
dev-server.js:60[HMR] Waiting for update signal from WDS...
warning.js:45Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.warning @ warning.js:45
client:28[WDS] Hot Module Replacement enabled.
RelayPendingQueryTracker.js:162Server request for query `HomePage` failed for the following reasons:

1. connect ECONNREFUSED 127.0.0.1:7474
   nt02xq35m on Viewer{_usersqc3e1o:users(first:10){edges{curso
                       ^^^_markAsRejected @ RelayPendingQueryTracker.js:162
```

is it because `Neo4j` not populated?

thanks.
bsr

**Comment by vslinko** [comment]
Hello, 

Looks like neo4j is not runned at all.

First of all, You need to configure neo4j to disable authentication and run neo4j server. 

After that you need to run `./bin/load_fixtures` to populate database.

And you should run `npm start` to start server.

**Comment by bsr203** [comment]
thanks it worked!!!

now what are the credentials to login for user1@example.com and user2@example.com

:-)

thanks a ton for the quick reply.

**Comment by vslinko** [comment]
https://github.com/vslinko/ripster/commit/cfc15a0acc0f57f6f695add09c7158bec9bf815b

**Comment by bsr203** [comment]
thanks for your effort on maintaining this project as it is a great learning source.. cheers..bsr
