### ISSUE TITLE
technical details #2

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#14]
Hi,

couple of qns.
1. frontend: What does the decorator `childrenToProps` do? I see it copy all children as pass it as props, but why?
2. graphql : schema/index.js

```
const refCreators = {
  rootQuery,
  rootMutation,
  ...types,
};

const {nodeInterface, nodeField} = nodeDefinitions(
  (globalId, {rootValue}) => {
    const {type, id} = fromGlobalId(globalId);

    return rootValue.loaders[type].load(id);
  },
  (object) => {
    const label = object.labels[0];
    const refKey = label[0].toLowerCase() + label.slice(1);

    return refs[refKey]; // eslint-disable-line no-use-before-define
  }
);

const refs = Object.keys(refCreators)
  .reduce((acc, key) => (
    acc[key] = refCreators[key](acc),
    acc[key + 'Connection'] = connectionDefinitions({
      name: acc[key].name,
      nodeType: acc[key],
    }).connectionType,
    acc
  ), {nodeInterface, nodeField});
```

i)  `const label = object.labels[0];` where are this `labels` set? 
ii) can you please explain the `reduce` function. I could see that you are adding `connection` automatically to all the rootQuery, rootMutation and types. why do we need to add connection to all, but not just to query types. I am totally confused as why the reduce is not in the form

reduce((a, b) => a + b)
reduce((a, b) =>  { ..., return a + b})

```
  .reduce((acc, key) => (     //-- is this a function (no curley !!) or a tuple ??
    acc[key] = refCreators[key](acc),
    acc[key + 'Connection'] = connectionDefinitions({
      name: acc[key].name,
      nodeType: acc[key],
    }).connectionType,
    acc
  ), {nodeInterface, nodeField});  //--> initial value, so include them too..

```

3.) How do you plan to use redux along with relay. IS redux is for local state only or you think it is better to keep a copy of all state changes for debugging etc.

sorry, I am new to frontend development and JS.

thanks again :-)

**Comment by vslinko** [comment]
> frontend: What does the decorator childrenToProps do? I see it copy all children as pass it as props, but why?

It makes possible to have named children.

```
<HomePage>
  <UserInfoForm key="form" /> {/* this element is available in this.props.form inside HomePage */}
</HomePage>
```

**Comment by vslinko** [comment]
> i) const label = object.labels[0]; where are this labels set? 

`labels` field goes from neo4j database response.

**Comment by vslinko** [comment]
> why do we need to add connection to all, but not just to query types

I want to have all connections predefined to stop thinking about is that type have a connection.

**Comment by vslinko** [comment]
> I am totally confused as why the reduce is not in the form

I'm using comma operator. You could read more about that here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

```
(a,b) => (a(), b())
// is equivalent to
(a, b) => {
  a();
  return b();
}
```

**Comment by vslinko** [comment]
> How do you plan to use redux along with relay. IS redux is for local state only or you think it is better to keep a copy of all state changes for debugging etc.

Yes, redux only for local state.
Somewhen in future, when someone will invent `redux-relay`, I'll use it.

**Comment by bsr203** [comment]
thanks for your time and helping out.
