### ISSUE TITLE
add unit test support

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#16]
Hi,

Is there a plan to add unit test support. You can see my attempt here https://github.com/vslinko/ripster/pull/15

but, one issue is that we use relative path in local imports through webpack alias, which cannot be resolved by mocha + babel. So, if you uncomment the code in the test file it throws error. Do you have a better way to do this through webpack ?

thanks,
bsr

**Comment by vslinko** [comment]
Yes, I commented in #15
We could continue discussion in #15 and prepare this PR for merge, if you have time for that.

**Comment by bsr203** [comment]
I haven't seen it, and will use it shortly and integrate with ripster. will update then.

**Comment by bsr203** [comment]
just adding some notes. I saw you used `tape` already for e2e test, and may also better to use for unit test. THis post by Eric Elliott convinced me.

https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.dqybk1izj

he also pointed to this boiler plate and not sure anything we can adapt from

https://github.com/cloverfield-tools/prod-module-boilerplate/blob/master/package.json

cheers.

**Comment by vslinko** [comment]
Main problem that we should to solve for unit tests support is integration between webpack and test runner, namely:
1. properly handle css imports;
2. properly handle webpack's exclusive features like `require.context` and `require.ensure`.

**Comment by bsr203** [comment]
yup, with mocha, I did something like.

```
var styles;
if (process.env.NODE_ENV !== 'test') {
   styles = require('./HomePage.scss');
} else{
   styles = {
    container: "container",
  }
}

```

at least it allow to use the file in test without webpack. But not sure about testing class properties.

Also, we may ended up using relative paths for import as webpack alias won't work. I started using relative path, bit of a pain, but less magic I guess :-)

**Comment by bsr203** [comment]
also, for `route` registration and all we could make it explicit so no need to use `require.context`. we may export it to the component `index` file, then import from it. It is fine to do bit of extra manual work to avoid the magic and support of lean testing. thanks.

**Comment by vslinko** [comment]
> also, for route registration and all we could make it explicit so no need to use require.context. we may export it to the component index file, then import from it. It is fine to do bit of extra manual work to avoid the magic and support of lean testing. thanks.

I don't think it's good idea because I'm sure that spending time on integration is better than spending time on adding new features to the index files.

**Comment by vslinko** [comment]
> at least it allow to use the file in test without webpack. But not sure about testing class properties.

We shouldn't think about such hacks when we're working on feature.

**Comment by vslinko** [comment]
I'm trying to integrate tape with webpack right now.

**Comment by vslinko** [comment]
Check out https://github.com/vslinko/ripster/commit/15cd966711d47ad25f5b4efe0cca6265a7ea89a8

**Comment by vslinko** [comment]
Also, unit tests added to gui server mode: `NODE_ENV=test npm start`

**Comment by bsr203** [comment]
thanks. pretty impressive you got it working. can I propose to keep the tests in a folder within the entities (components, reducers,..), so they live close to the source to edit them together and easy to import. similar to in this pull request https://github.com/vslinko/ripster/pull/15/files

Also, can you please add an example of a react shallow render test if you have time. I will also look into this.

I am going to try right away and give you feedback. cheers.

**Comment by bsr203** [comment]
Hello. I never used the gui server mode before and was running as `node server` so far. I see 4 blocks, where webserver and others show stdout messages. but, the test block is empty. Is the GUI runs on watch mode so any modification on the test re run immediately? 

I started it like `NODE_ENV=test npm start`. A manual run with `npm run test-unit` showed the tape output.

Also, https://github.com/substack/faucet would be a good addition ?

**Comment by bsr203** [comment]
sorry not sure how I see some messages (error regarding Graphql validation) now. When I modify the test, there is no feedback/update. still digging.

Edit:
I can see the test ran in the `test` GUI window as well. but, not sure it is in watch mode as it doesn't re run. Also, how to clear the block, or scroll through it. I am reading the source to find about it.

**Comment by vslinko** [comment]
> thanks. pretty impressive you got it working. can I propose to keep the tests in a folder within the entities (components, reducers,..), so they live close to the source to edit them together and easy to import. similar to in this pull request https://github.com/vslinko/ripster/pull/15/files

Agreed: https://github.com/vslinko/ripster/commit/679e9beaf2fc7f1b06d1dfb0bac3897b34da76d5

**Comment by vslinko** [comment]
> Also, can you please add an example of a react shallow render test if you have time. I will also look into this.

https://github.com/vslinko/ripster/commit/8bd4c64a3cc62e48b86f2b4c62787ece5aac20cc

**Comment by vslinko** [comment]
> I can see the test ran in the test GUI window as well. but, not sure it is in watch mode as it doesn't re run. Also, how to clear the block, or scroll through it. I am reading the source to find about it.

Test window is simply waiting for `listening` word in the other windows and then re-runs tests.
1. https://github.com/vslinko/ripster/blob/8bd4c64a3cc62e48b86f2b4c62787ece5aac20cc/server/createMonitor.js#L16-L18
2. https://github.com/vslinko/ripster/blob/8bd4c64a3cc62e48b86f2b4c62787ece5aac20cc/server.js#L25
3. https://github.com/vslinko/ripster/blob/8bd4c64a3cc62e48b86f2b4c62787ece5aac20cc/server/testRunner.js#L40

**Comment by bsr203** [comment]
Thanks. It was working, but I didn't realize I had to wait 5 -10 sec to see an output there. I think we have a perfect setup now which allows to use webpack facilities. Only drawback it is bit slow. I was using the setup as in https://github.com/prometheusresearch/react-forms/tree/2.0.0 by @andreypopp so far, which re runs the test in milli seconds, so the feedback lis instantaneous. Is there a way to incorporate HMR for testing so we don't have to wait to do a full build.

On a side note, I saw you use ReduxForm. react-forms has slightly different purpose and make you just focus on the layout. We could trivially post the data to a redux store. I highly recommend react-forms@2.0.0 (ONLY use 2.0.0 branch). It is a great package by a smart guy like you :-) 

thanks for all your hard work and time to support us. Cheers.

**Comment by vslinko** [comment]
> Thanks. It was working, but I didn't realize I had to wait 5 -10 sec to see an output there. I think we have a perfect setup now which allows to use webpack facilities. Only drawback it is bit slow. I was using the setup as in https://github.com/prometheusresearch/react-forms/tree/2.0.0 by @andreypopp so far, which re runs the test in milli seconds, so the feedback lis instantaneous. Is there a way to incorporate HMR for testing so we don't have to wait to do a full build.

Yes, webpack takes a lot of time to make a build. And that behaviour could be fixed by removing webpack from testing process. At least it's working right now.
I already have thoughts about reducing compile time https://github.com/vslinko/ripster/issues/31 https://github.com/vslinko/ripster/issues/32 and I will investigate more on this.

**Comment by bsr203** [comment]
thanks. will track further on those issues.

**Comment by vslinko** [comment]
> On a side note, I saw you use ReduxForm. react-forms has slightly different purpose and make you just focus on the layout. We could trivially post the data to a redux store. I highly recommend react-forms@2.0.0 (ONLY use 2.0.0 branch). It is a great package by a smart guy like you :-)

I don't like idea to use components at this way and I know that @andreypopp have an other opinion on that :smile: 
But thank you for the reference.
