### ISSUE TITLE
react-intl

### ISSUE THREAD

**Issue by vslinko** [vslinko/ripster#17]

**Comment by ooflorent** [comment]
Is there any reason why? We use `react-intl@2.0.0-pr2` and found it not really convenient. While `Formatted*` components are simple to use, the lack of imperative API is really an issue. Even with `injectIntl` helper.

Using `react-intl` means that you can no longer do:

``` js
<input placeholder={ formatMessage("some.message") } />
```

You have to use `defineMessages` or wrap your id:

``` js
<input placeholder={ formatMessage({id: "some.message"}) } />
```

**Comment by vslinko** [comment]
I'm tried `react-intl@2.0.0-pr2` on one of my projects and I like it more than my current solution.
I found that `formatMessage({id: "some.message", defaultMessage: "Some Message"})` really fits to me.

Second reason is that `react-intl` maintained by other people, not me :smile:

**Comment by vslinko** [comment]
Closed by https://github.com/vslinko/ripster/commit/386b15c4fdb028b6f55892e029d80af708b52d57
