### ISSUE TITLE
Anonymous user can not make operation

### ISSUE THREAD

**Issue by alexandrethsilva** [vslinko/ripster#25]
Hi @vslinko, thanks for sharing with us all this neat experiment you're working on!

I'm basing a lot of my early work on an experimental project of my own on Ripster and having almost all of it setup I'm basically with one last issue before I can get started on building it.

The issue is mostly with the ACL part, which uses access-control (also done by you) and even though I get the principle, I'm not really understand how it works in practice.

I suppose the `checkAccess` function is the key part on my issue, but I didn't really get why my operation is being done by an Anonymous user even though I have created a session before attempting the OP_UPDATE

It keeps returning

```
{
  "data": {
    "setUserEmail": null
  },
  "errors": [
    {
      "message": "Forbidden: Anonymous user can not make operation \"OP_UPDATE\" on object (:User) with id \"10\"",
      "locations": [
        {
          "line": 1,
          "column": 55
        }
      ]
    }
  ]
}
```

I'm trying to debug since a couple days, but without luck...
Do you have any tips on this? I know it's a small excerpt, but the ACL code is so fragmented throughout the project that I didn't really know which part of it would be valid for you to help me out.

Just let me know if there's some other part of the code that you'd like me to put here so that you can assist.

Thanks a lot and keep up the cool work!

PS. The `setUserEmail` is correct. I changed the naming a little on my project to make it more unique, since there will be emails not only for users, but also for other entities...

**Comment by alexandrethsilva** [comment]
Hey, I solved it now. It was an embarrassing typo on the part of the code where I was setting the cookie. :smile:

**Comment by vslinko** [comment]
Hi. It's good to hear that you solved your problem :smile:
