### ISSUE TITLE
Try css-modules

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#26]
Like to know your view on using css modules to avoid global namespace and BEM like naming convention.

example:
 https://github.com/css-modules/postcss-modules-local-by-default
https://github.com/css-modules/webpack-demo

Ref:
http://glenmaddern.com/articles/css-modules
https://www.youtube.com/watch?v=BfzjuhX4wJ0&feature=youtu.be&t=3h27m53s

haven't tried, just saw:
https://github.com/gajus/react-css-modules

**Comment by vslinko** [comment]
Yes, we will use postcss. I just need week or two to integrate it.

**Comment by vslinko** [comment]
Closed by https://github.com/vslinko/ripster/commit/72c7949ec60e3571c9ff2a605c21b00001823f48
