### ISSUE TITLE
Use redux-simple-router instead of redux-router

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#28]
Do you think since we use relay, may be a light weight approach is enough. This discussion gave me that impression.

https://github.com/rackt/redux-router/issues/172

I see you had to fork `redux-router` to make it work in the last dependency update :-)
thanks for your effort.

Cheers.
bsr

**Comment by vslinko** [comment]
I want to be able to use server side rendering in future. As I saw redux-simple-router recommending to use redux-router for SSR. So I think we should stay on redux-router.

**Comment by bsr203** [comment]
thanks. closing then. we may revisit later.

**Comment by bsr203** [comment]
http://jlongster.com/A-Simple-Way-to-Route-with-Redux
https://github.com/jlongster/redux-simple-router/issues/13

we may revisit once above example is complete

**Comment by vslinko** [comment]
I can't find any reason to migrate from `redux-router` to `redux-simple-router`.
Could you provide some reasons for me?

**Comment by bsr203** [comment]
:-) not really. After reading about `redux-simple-router` and the blog post, it is simpler and doesn't proxy the features of `react-router`. So can use the latest versions of react-router without worrying about `redux-router`. Basically, in the realm of increasing dependencies and constant changes, keep me sane if  less things to think about :-)

**Comment by vslinko** [comment]
Ok, you're free to reopen issue after they're complete the example and I'll see. :smile:

**Comment by bsr203** [comment]
thanks. front end development is really crazy. I recently started with it and was a C++, C# guys prior to that. Currently I use `go` for my backend, and programs written 5 - 6 years back, when they first released, still works with very minimal changes. At the same time nothing in frontend lasted for more than few months.

 `grunt -> gulp -> browserify -> webpack -> ??? `
 `javascript -> es5 -> typescript -> (what else clojurescript, coffeescript, purescript) es6 -> babel -> es7 -> ...`
`n other framework -> angular 1.x -> react -> angular 2.x -> react -> cycle .... `
`css -> less/sass/scss -> css next -> inline style (radium and co...) -> webpack module `
`{bower -> millions of npm packages}`

and chasing other non value adds like yeoman, ...

css frameworks ...

:-)  you get the point :-)

**Comment by bsr203** [comment]
just updating this issue with relevant info

as seen in this commit https://github.com/acdlite/redux-router/commit/e4912bae9fd735dedb0405220badb01552e59380

`redux-router is moved out of rackt` and recommend using `redux-simple-router`

**Comment by vslinko** [comment]
Ok, you convinced me :-)
Unfortunately, I can't spend time on this issue right now.
Could you make PR with migration to `redux-simple-router`?

**Comment by bsr203** [comment]
ok, will try. cheers :-) but I have no idea about usage with serverside as I don't use it. IS that ok with you just having client side ?

**Comment by bsr203** [comment]
https://github.com/vslinko/ripster/pull/46

As I said, client side routing works well with my app. I don't use server side rendering. Please verify.

**Comment by vslinko** [comment]
Ripster doesn't support server side rendering because Relay doesn't support server side rendering.

**Comment by vslinko** [comment]
Closed by #46
