### ISSUE TITLE
redux devtool

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#30]
Hi, I saw the support for it is removed. Is it because it is not compatible with the updates or is not quite useful. 

have you tried https://github.com/zalmoxisus/redux-devtools-extension

thanks.
bsr

**Comment by vslinko** [comment]
Compatibility with the updates it is an occasion.
The reason is that we did not use them at all.

**Comment by vslinko** [comment]
And no, we didn't tried the extension.

**Comment by vslinko** [comment]
If you want I could add `window.devToolsExtension ? window.devToolsExtension() : f => f` to support the extension.

**Comment by vslinko** [comment]
Closed by https://github.com/vslinko/ripster/commit/eac4099856e6a88ce6aefc6d7d5ff014b8daa33d

**Comment by bsr203** [comment]
@vslinko thanks. ya, I tried that extension after I posted this issue, and works much better and not intrusive. I too never used redux devtool as it is bit overwhelming with the number of actions and get lost. But, sometimes I just wanted to see the current state and glad we can do that now. Thanks again for your effort on this package. Cheers.
