### ISSUE TITLE
error loading home page

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#33]
On the latest master branch, I get this error

![screen shot 2015-11-21 at 10 47 23 pm](https://cloud.githubusercontent.com/assets/1966521/11321959/2bec8386-90a2-11e5-824b-e0f74c4b9072.png)
![screen shot 2015-11-21 at 10 48 23 pm](https://cloud.githubusercontent.com/assets/1966521/11321960/2bed8c7c-90a2-11e5-9817-9bc0aa6e19b7.png)

**Comment by vslinko** [comment]
Are you using Chrome Canary? Looks like it's a bug in Chome Canary.

**Comment by vslinko** [comment]
Forwarded issue to `react-intl`: https://github.com/yahoo/react-intl/issues/228

**Comment by bsr203** [comment]
good catch. It only happens on Canary.
