### ISSUE TITLE
https://github.com/substack/faucet

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#35]
I have seen it used often on tape based test setup and do you think it helps to give better visual clues about failure and removes boilerplate messages. it looks lightweight.

**Comment by vslinko** [comment]
You can use faucet manually: `./bin/unit_tests | faucet`

**Comment by vslinko** [comment]
I can't use faucet inside `./bin/unit_tests` because blessed doesn't handle color output properly.

**Comment by bsr203** [comment]
thanks, i will use it as you suggested.

**Comment by vslinko** [comment]
Added faucet to package.json https://github.com/vslinko/ripster/commit/80554e9fbd018dac026b688219c0f11666eddd4c
So, when you running `npm run test-unit` it will use faucet
