### ISSUE TITLE
stateless functional components and `react` import

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#40]
Please see the details here http://stackoverflow.com/questions/33422651/stateless-functional-components-and-react-import

I am not a pro of webpack and please let me know whether we can incorporate the answer given.

Also, can we exclude `react` from build so that we can improve initial build time. not sure how it affect sourcemaps (typically react stack traces are not quite useful).

thanks.

**Comment by vslinko** [comment]
First of all, I have a babel plugin for this issue: https://github.com/vslinko/babel-plugin-react-require :smile: 

But I don't use this plugin because now I want to declare `import React` explicitly.

**Comment by bsr203** [comment]
thanks. I too prefer declaring `React` explicitly, but was getting error due to wrong source order for functional components, and warning with eslint if I only use functional component on that file. I could use `// eslint-` comment to suppress unused import but thought may better to make sure that `react` loads first. With your response, I guess I too stick with using it explicitly. :-) thanks for your help as always :-)
