### ISSUE TITLE
Better offline support

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#42]
throwing this out here to see your take on improving performance and responsiveness using this.

https://github.com/NekR/offline-plugin

http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org

I see relay error when my graphql server goes offline, and wonder more elegant way to handle this with offline strategy.

**Comment by vslinko** [comment]
This is a good topic to investigate, but right now I have no free time for this.
You could try to make contribution to this project by adding offline support.

**Comment by bsr203** [comment]
will investigate :-) we can keep it open then to get more feedback as well.. thanks.

**Comment by bsr203** [comment]
just saw this repo the second trending in github today. Didn't try, but has all the offline goodies 

https://github.com/mxstbr/react-boilerplate

**Comment by vslinko** [comment]
Thank you. I'll see.
