### ISSUE TITLE
search / field lookup example

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#44]
Hi, I can't really figure out the best way to incorporate search functionality with `ripster` or in a relay app. In all the examples I've seen, queries are done with relay container, so the request is sent initially. I may ask for new data with `relay.setVariables`, but below flow sounds more logical.

user fills the form ->  a redux action is fired upon submission ->  action invokes a relay network request -> results are available when the promise resolves

I have only seen mutation done this way. It would be great to know how you would approach this. My assumptions may be overcomplicating things. but, I may be using this feature at many places and needs to do it properly. For example, a popup lookup/search dialog for user, based on different attributes.

greatly appreciate any help to get me started.

thanks.
bsr.

**Comment by vslinko** [comment]
Hello. We're already done search functionality in our product. 
I'm published our implementation for you: https://gist.github.com/vslinko/3f877c2415464ecc7af6

**Comment by bsr203** [comment]
Wow! you are a lifesaver :-) will try it out... thanks a ton.

**Comment by bsr203** [comment]
Hi.  If I understood right, invoking the action through search box causes a redirect to search results page and for which the relay container is created dynamically with the search parameters. That is really good, but do you do search without redirect. Say you want add `good` to container/cart/.. so you provide a search modal/popup where the user enters the query parameters. Results are displayed on the same modal, and user selects the good and closes the modal. The original screen uses the selected good for further processing. Do you think we can adapt the code you provide to fit this flow.

Thanks again.

**Comment by vslinko** [comment]
I'm not sure that you can adapt that code, but instead of changing URL you could change redux state.

**Comment by bsr203** [comment]
thanks. I didn't really thought about results section as a new relay container. A big mental shift from request/response model I used to. :-) thanks again.

**Comment by bsr203** [comment]
hi @vslinko `propsToRelay` causes issue when I pass non serializable props through the params (like route children prop). gets error

```
RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at stableStringify (http://localhost:3000/frontend.js:49418:16)
```

I use it like 

```
export default compose(
  propsToRelay(props => ({
    children: props.children,
   // and other params
  })),
  relay({
    initialVariables: {
```

if I don't pass `children` explicitly, it is not available to the component.
is there a way to do this?

**Comment by vslinko** [comment]
Relay documentation says that you shouldn't pass anything to `RelayContainer`.
But you can do that if you really want.
So, I created this decorator for rare cases when `initialVariables` should get value from the parent props (mostly from the Redux container).

As I see, in your case `children` is defined not for `initialVariables`, so your case is invalid for this decorator.

**Comment by bsr203** [comment]
thank you. I will not use the decorator in this specific case.
