### ISSUE TITLE
better history import

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#47]
From the doc
https://github.com/rackt/history/blob/master/docs/GettingStarted.md

we may replace the import from

`import { createHistory } from 'history';
`

to

`import createHistory from 'history/lib/createBrowserHistory';
`

Also, about the `_k` query params. https://github.com/rackt/history/issues/163

**Comment by vslinko** [comment]
1. Yes, we should change import.
2. What about `_k`?

**Comment by bsr203** [comment]
1. I though of a quick PR but I may need to update my setup again, so will try next time or you could just include it with your next update.
2. I started noticing `_k` query parameter with url after the last change. just wanted a record of it. Nothing to be done now, but hope they get rid of it soon.

**Comment by bsr203** [comment]
fixed by https://github.com/vslinko/ripster/pull/50

**Comment by vslinko** [comment]
As I already wrote, could you create a separate PR fixing this problem?

**Comment by vslinko** [comment]
> I started noticing _k query parameter with url after the last change. just wanted a record of it. Nothing to be done now, but hope they get rid of it soon.

Fixed by https://github.com/vslinko/ripster/commit/7dd8d4ba0471725cfe36bff149f33817baf806c3
