### ISSUE TITLE
Properly handle all kinds of errors

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#48]
hi,

I was looking for a way to capture all the relay/graphql error and handle them appropriately (push to redux store to show flash message, ...). As per this thread https://github.com/facebook/relay/issues/481, `DefaultNetworkLayer`is  supposed to be an example implementation and we may have to customize to handle request/response properly. Do you happen to have a better implementation or any plan for enhancing it.

Cheers.

**Comment by vslinko** [comment]
Hello. Of course I have plans to properly handle errors.
I should done that before our product MVP release, so it will be done in next 1-2 months.

**Comment by vslinko** [comment]
I keep this issue as general task.

**Comment by bsr203** [comment]
:-) great. thank you

**Comment by bsr203** [comment]
for the UI, I kinda like this approach https://github.com/7rulnik/evil-martians-test-project

**Comment by bsr203** [comment]
hi, I could get it working with 
1. UI and redux logic from https://github.com/7rulnik/evil-martians-test-project
2. A custom `RelayNetworkLayer` (just extends DefaultNetworkLayer and sends an action on error for now).

if you like the approach, I can submit a PR.

**Comment by vslinko** [comment]
Yes, please. It would be awesome.

**Comment by bsr203** [comment]
notification support. .https://github.com/vslinko/ripster/pull/50
