### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vslinko** [vslinko/ripster#49]
I want to write some useful documentation.

**Comment by evanwchurchill** [comment]
Hey @vslinko I really like the look of this stack. Are you available at all this week to discuss what you've done here with me? I'm looking to implement something similar with a Neo4j DB hooked up to a react-redux frontend, and I'd love to hear your perspective as to how you arrived with this stack.

**Comment by vslinko** [comment]
Thank you, @evanwchurchill
You could create a new issue with your questions and I'll try to answer them.
