### ISSUE TITLE
babel6 support

### ISSUE THREAD

**Issue by bsr203** [vslinko/ripster#52]
I see the changes in the [branch](https://github.com/vslinko/ripster/tree/babel6) you created for this, and please let me know is there still plugins/dependencies which doesn't work with babel6. thanks.

**Comment by bsr203** [comment]
you can see my attempt here. there needs to be bit mpre work on this, but functionally looks good. https://github.com/vslinko/ripster/pull/54 Can't wait to hear your suggestions.

**Comment by vslinko** [comment]
Hello.
As I know, right now nothing stops us from using babel6.
I'll update babel6 branch and check what are left.

**Comment by vslinko** [comment]
Let's continue to talk about babel6 in main PR #45
