### ISSUE TITLE
Localization API for GraphQL Server

### ISSUE THREAD

**Issue by vslinko** [vslinko/ripster#9]

**Comment by bsr203** [comment]
can you please comment on what you plan to do with this item? I use a different backend, and wonder what all I need to think ahead. thanks.

**Comment by vslinko** [comment]
First of all, we need pass `locale` cookie from client via webserver to graphql server.
I guess `proxy-middleware` [already handle this](https://github.com/vslinko/ripster/blob/master/src/webserver/index.js#L21). 

Second of all, we need to pass `locale` as `rootValue`.
It's [already done](https://github.com/vslinko/ripster/blob/master/src/graphql/index.js#L39).

After all those manipulations we need to pass localization functions with prebound locale to `rootValue`.
This issue about providing `formatjs.io` functions within `rootValue`.

Public API will be like that:

``` js
role: {
  type: GraphQLString,
  resolve: (user, args, info) => {
    return info.rootValue.formatMessage(user.properties.role);
  },
},
```

**Comment by bsr203** [comment]
Thank you. so using formatted messages in resolve means we will be doing translation both at server and client (like we do in forms). When is it appropriate to do at server instead of client?

**Comment by vslinko** [comment]
All schema fields that defined on backend should be translated on backend.
All text labels that defined on frontend should be translated on frontend.

**Comment by vslinko** [comment]
`query { item { title } }` should be translated on backend.
`Item titile is "{title}"` should be translated on frontend.

**Comment by bsr203** [comment]
thank you. that make sense. Cheers.
